// <auto-generated />
using System;
using EF_CodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CodeFirst.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_CodeFirst.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            GradeName = "Math",
                            Section = "A",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 2,
                            GradeName = "Science",
                            Section = "B",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 3,
                            GradeName = "English",
                            Section = "A",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 4,
                            GradeName = "History",
                            Section = "B",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 5,
                            GradeName = "Art",
                            Section = "A",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 6,
                            GradeName = "Music",
                            Section = "B",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 7,
                            GradeName = "Physical Education",
                            Section = "A",
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            DateOfBirth = new DateTime(2005, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 1.70m,
                            StudentName = "Alice",
                            Weight = 55.5f
                        },
                        new
                        {
                            StudentID = 2,
                            DateOfBirth = new DateTime(2004, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 1.82m,
                            StudentName = "Bob",
                            Weight = 68f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
